version: '2'
services:
  frontend:
    build:
      context: .
      dockerfile: ./.docker/frontend.prod.dockerfile
    ports:
      - "80:80"
    networks:
      - rpthreadtracker-network
  backend:
    build:
      context: .
      dockerfile: ./.docker/backend.prod.dockerfile
    ports:
      - "29564:80"
    networks:
      - rpthreadtracker-network
  sqldb:
    build:
      context: .
      dockerfile: ./.docker/sqldb.dockerfile
    networks:
      - rpthreadtracker-network
networks:
  rpthreadtracker-network:
    driver: bridge
