version: '2.4'
services:
  frontend:
    build:
      context: .
      dockerfile: ./.docker/frontend.test.dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./RPThreadTrackerV3.FrontEnd:/usr/src/app
    networks:
      - rpthreadtracker-network
  backend:
    build:
      context: .
      dockerfile: ./.docker/backend.test.dockerfile
    ports:
      - "29564:80"
    volumes:
      - ./RPThreadTrackerV3.BackEnd:/app
    networks:
      - rpthreadtracker-network
  tumblrclient:
    build:
      context: .
      dockerfile: ./.docker/tumblrclient.test.dockerfile
    ports:
      - "58075:80"
    volumes:
      - ./RPThreadTracker.BackEnd.TumblrClient:/app
    networks:
      - rpthreadtracker-network
networks:
  rpthreadtracker-network:
    name: "rpthreadtracker-network"
