version: '2'
services:
  frontend:
    build:
      context: .
      dockerfile: ./.docker/frontend.dev.dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./RPThreadTrackerV3.FrontEnd:/usr/src/app
    networks:
      - rpthreadtracker-network
  backend:
    build:
      context: .
      dockerfile: ./.docker/backend.dev.dockerfile
    ports:
      - "29564:80"
    volumes:
      - ./RPThreadTrackerV3.FrontEnd:/usr/src/app
    networks:
      - rpthreadtracker-network
  # sqldb:
  #   image: "microsoft/mssql-server-linux"
  #   environment:
  #     SA_PASSWORD: "Your_password123"
  #     ACCEPT_EULA: "Y"
  #   volumes:
  #     - ./RPThreadTrackerV3.BackEnd/SQL:/scripts
  #   networks:
  #     - rpthreadtracker-network
networks:
  rpthreadtracker-network:
    driver: bridge
